spring.application.name=bankmanagementsystem

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_management_system
spring.datasource.username=postgres
spring.datasource.password=developer@542

jwt.secret=rBe/2ZTD4t6jZaDZAmhpTj4S8Mr+QOOUEpPY4Na6RSM=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true